version: "3"
services:
  mysql-db:
    container_name: mysql
    image: mysql:5.7.27
    volumes:
      - /mnt/mysql:/var/lib/mysql
      - /home/centos/db_scripts:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw

  selenium-hub:
    container_name: selenium-hub
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"

  web:
    container_name: api-server
    build: .
    depends_on:
      - mysql-db
    ports:
      - "5000:5000"